version: "1.0"
description: "预发环境配置"

# 继承基础配置
extends: "../base/database.yaml"

# 预发环境特定配置
database:
  main:
    host: "${STAGING_DB_HOST}"
    port: "${STAGING_DB_PORT}"
    database: "${STAGING_DB_NAME}"
    ssl_enabled: true
    connection_pool_size: 10

logging:
  level: "INFO"
  console_output: true
  file_rotation: true
  max_file_size: "50MB"
  backup_count: 5

agents:
  supply_chain:
    parameters:
      temperature: 0.6
      max_tokens: 1500
      debug: false
  unified:
    parameters:
      temperature: 0.6
      max_tokens: 1500
      debug: false

# 预发环境特定设置
debug_mode: false
mock_external_services: false
enable_test_endpoints: true
security_headers: true
rate_limiting: false
monitoring_enabled: true