business_process: "\n    生物质锅炉智能寻源完整流程，包括：\n    1. 市场调研与分析：收集生物质燃料市场信息，分析价格趋势和供应情况\n\
  \    2. 供应商评估：评估潜在供应商的资质、信誉、供货能力和质量保证\n    3. 成本效益分析：分析不同供应商的报价，计算总体拥有成本\n    4.\
  \ 质量控制标准制定：制定生物质燃料质量标准和检测方法\n    5. 供应链优化：设计最优的采购、运输和存储方案\n    6. 风险评估与管理：识别供应链风险并制定应对措施\n\
  \    7. 合同谈判与签订：与选定的供应商进行合同谈判\n    8. 实施与监控：执行采购计划并持续监控供应链表现\n    "
crewai_config:
  agents:
  - allow_delegation: false
    backstory: 你是一位经验丰富的供应链规划专家，拥有超过10年的行业经验，擅长分析复杂供应链问题并制定创新解决方案。
    goal: 根据业务需求制定最优的供应链规划和策略
    max_iter: 25
    max_rpm: 1000
    name: 供应链规划师_planner
    role: 负责制定供应链战略和规划
    tools: []
    verbose: true
  - allow_delegation: false
    backstory: 你是一位专业的供应链数据分析师，精通各种数据分析工具和方法，能够从复杂数据中提取有价值的信息。
    goal: 深入分析供应链数据，识别问题和机会，提供数据驱动的洞察
    max_iter: 25
    max_rpm: 1000
    name: 供应链分析师_analyst
    role: 负责分析供应链数据和趋势
    tools: []
    verbose: true
  - allow_delegation: false
    backstory: 你是一位经验丰富的供应链执行专家，擅长将计划转化为实际行动，能够有效应对执行过程中的各种挑战。
    goal: 高效执行供应链计划，确保各项任务按时完成
    max_iter: 25
    max_rpm: 1000
    name: 供应链执行者_executor
    role: 负责执行供应链计划和任务
    tools: []
    verbose: true
  - allow_delegation: false
    backstory: 你是一位严谨的供应链审查专家，具有敏锐的洞察力，能够发现潜在问题并提出改进建议。
    goal: 全面审查供应链流程和结果，确保质量和效率
    max_iter: 25
    max_rpm: 1000
    name: 供应链审查者_reviewer
    role: 负责审查供应链流程和结果
    tools: []
    verbose: true
  description: "基于业务流程 '\n    生物质锅炉智能寻源完整流程，包括：\n    1. 市场调研与分析：收集生物质燃料市场信息，分析价格趋势和供应情况\n\
    \    2. 供应商评估：评估潜在供应商的资质、信誉、供货能力和质量保证\n    3. 成本效益分析：分析不同供应商的报价，计算总体拥有成本\n   \
    \ 4. 质量控制标准制定：制定生物质燃料质量标准和检测方法\n    5. 供应链优化：设计最优的采购、运输和存储方案\n    6. 风险评估与管理：识别供应链风险并制定应对措施\n\
    \    7. 合同谈判与签订：与选定的供应商进行合同谈判\n    8. 实施与监控：执行采购计划并持续监控供应链表现\n    ' 生成的供应链优化团队"
  manager_role: null
  memory: true
  name: 供应链优化团队
  process: sequential
  tasks:
  - agent: 供应链规划师_planner
    context: []
    description: 分析当前供应链状况，识别关键问题和机会
    expected_output: 详细的供应链分析报告，包括现状、问题和机会
    name: 供应链分析_1
    tools: []
  - agent: 供应链分析师_analyst
    context: []
    description: 根据分析结果制定供应链优化规划
    expected_output: 全面的供应链优化规划，包括目标、策略和实施步骤
    name: 供应链规划_2
    tools: []
  - agent: 供应链执行者_executor
    context: []
    description: 执行供应链规划，监控实施进度
    expected_output: 供应链执行报告，包括进度、成果和问题
    name: 供应链执行_3
    tools: []
  - agent: 供应链审查者_reviewer
    context: []
    description: 审查供应链执行结果，评估效果并提出改进建议
    expected_output: 供应链审查报告，包括效果评估和改进建议
    name: 供应链审查_4
    tools: []
  verbose: true
generated_at: '2024-01-01T00:00:00Z'
